version: '3'

services:

  server:
    build: docker/server
    restart: always
    depends_on:
      - database
    ports:
      - $DOCKER_SERVER_PORT:80
    volumes:
      - ./server:/var/www/html

  database:
    build: docker/database
    restart: always
    volumes:
      - ./database:/var/lib/mysql